### ISSUE TITLE
Marker label query

### ISSUE THREAD

**Issue by mice-exp** [qualisys/paf-documentation#2]
Hello, I have exported for the first time a file using the Qualysis-Theia markerless PAF example. 
Is there documentation on the marker labels? I have the following list of markers but am having trouble matching them to the 19 markers [on the Theia3D documentation.](https://www.theiamarkerless.ca/docs/model.html?highlight=head) 
'LAB',  'LAR',  'LFA', 'LFT',  'LHA', 'LSK', 'LTH', 'LTO',  'RAR', 'RFA', 'RFT', 'RHA', 'RHE',   'RPV','RSK',  'RTA', 'RTH', 'RTO', 'VLB'
Thank you for your time!

**Comment by DocVi** [comment]
Hi!

Can you post your request in https://github.com/qualisys/paf-theia-markerless-example

Thanks
